### ISSUE TITLE
Bundler 2.0 does not immediately work, requires installation of another bundler.

### ISSUE THREAD

**Issue by cobbr2** [asdf-vm/asdf-ruby#110]
I've just started using `asdf` today, and found this remarkably confusing:
```
rcobb@rcobb-t480: (master) ~/tp$ asdf local ruby 2.5.1
rcobb@rcobb-t480: (master) ~/tp$ which bundle
/home/rcobb/.asdf/shims/bundle
rcobb@rcobb-t480: (master) ~/tp$ bundle --version
asdf: No version set for command bundle
you might want to add one of the following in your .tool-versions file:

ruby 2.5.3
ruby 2.6.2
rcobb@rcobb-t480: (master) ~/tp$ gem install bundler
Fetching: bundler-2.0.1.gem (100%)
Successfully installed bundler-2.0.1
1 gem installed
rcobb@rcobb-t480: (master) ~/tp$ bundle exec echo bar
Traceback (most recent call last):
	2: from /home/rcobb/.asdf/installs/ruby/2.5.1/bin/bundle:23:in `<main>'
	1: from /home/rcobb/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/home/rcobb/.asdf/installs/ruby/2.5.1/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
rcobb@rcobb-t480: (master) ~/tp$ gem uninstall bundler
Gem 'bundler' is not installed
rcobb@rcobb-t480: (master) ~/tp$ gem install bundler --version 1.17.3
Fetching: bundler-1.17.3.gem (100%)
Successfully installed bundler-1.17.3
1 gem installed
rcobb@rcobb-t480: (master) ~/tp$ bundle exec echo bar
bar
rcobb@rcobb-t480: (master) ~/tp$ gem uninstall bundler

Select gem to uninstall:
 1. bundler-1.17.3
 2. bundler-2.0.1
 3. All versions
> 2
Successfully uninstalled bundler-2.0.1
rcobb@rcobb-t480: (master) ~/tp$ bundle exec echo bar
bar
```

Operating system, etc:
```
rcobb@rcobb-t480: (master) ~/tp$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
rcobb@rcobb-t480: (master) ~/tp$ uname -a
Linux rcobb-t480 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
rcobb@rcobb-t480: (master) ~/tp$ asdf --version
v0.7.0
rcobb@rcobb-t480: (master) ~/.asdf/plugins/ruby$ cd ~/.asdf/plugins/ruby
rcobb@rcobb-t480: (master) ~/.asdf/plugins/ruby$ git log -n1  --oneline
f773da34715a (HEAD -> master, origin/master, origin/HEAD) Merge pull request #109 from damireh/update-to-latest-ruby-build
```

**Comment by SeanSith** [comment]
Please try updating to asdf v0.7.1 as it fixes a problem with locating shims. I had similar issues and that seemed to fix the issue for me.

**Comment by cobbr2** [comment]
Seems to have resolved the issue. Thanks, @SeanSith .

**Comment by simmel** [comment]
I had a similar problem which persisted even after upgrading asdf and asdf-ruby.
I ended up having to `asdf uninstall ruby 2.5.3 && asdf install ruby 2.5.3` and then it worked (for future reference).

**Comment by shadowmaru** [comment]
I had this exact problem with version 0.7.4 and ruby-2.5.0. Reinstalling also didn't work. Using bundler 1.17.3 right now.

**Comment by requnix** [comment]
This still happens on version 0.7.6 and ruby-2.5.0. Will switch to Bundler 1.x.

**Comment by Stratus3D** [comment]
@requnix did you try `asdf reshim` after installing bundler?

**Comment by requnix** [comment]
I tried reshimming, reinstalling, everything. What eventually got me past the problem was using `asdf exec …` for everything. It looked like it was installing it in the wrong place, but I can't confirm now because I abandoned `asdf` after running into problem after problem all day long.

**Comment by tennety** [comment]
Could be relevant: https://github.com/asdf-vm/asdf-ruby/issues/129 . Fixed the issue for me, doesn't seem to be an `asdf` problem.
