### ISSUE TITLE
macos+fishshell - Ruby 2.5.3 & Bundler - can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by robacarp** [asdf-vm/asdf-ruby#129]
I've been able to use asdf pretty well lately with several plugins, but asdf-ruby seems to have died on me this morning.

I'm seeing what looks like #121 as well, because every install reinstalls ruby-build.

```
> asdf uninstall ruby 2.5.3

> asdf install ruby 2.5.3
Downloading ruby-build...
Cloning into 'ruby-build-source'...
remote: Enumerating objects: 65, done.
remote: Counting objects: 100% (65/65), done.
remote: Compressing objects: 100% (38/38), done.
remote: Total 9777 (delta 26), reused 51 (delta 19), pack-reused 9712
Receiving objects: 100% (9777/9777), 2.08 MiB | 3.89 MiB/s, done.
Resolving deltas: 100% (6352/6352), done.
Note: checking out 'v20190615'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at ac92ec0 Merge pull request #1306 from olivierlacan/2-7-0-preview1
ruby-build: use openssl from homebrew
Downloading ruby-2.5.3.tar.bz2...
-> https://cache.ruby-lang.org/pub/ruby/2.5/ruby-2.5.3.tar.bz2
Installing ruby-2.5.3...
ruby-build: use readline from homebrew
Installed ruby-2.5.3 to /Users/user/.asdf/installs/ruby/2.5.3

> gem install bundler
Fetching: bundler-2.0.2.gem (100%)
Successfully installed bundler-2.0.2
Parsing documentation for bundler-2.0.2
Installing ri documentation for bundler-2.0.2
Done installing documentation for bundler after 4 seconds
1 gem installed

> bundle install
Traceback (most recent call last):
	2: from /Users/user/.asdf/installs/ruby/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/user/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/user/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

I'm on macos, and using fish-shell. I'm happy to help debug, but I'm not sure what the next step should be.

-------

Edit: I first hit this under asdf 7.2, and used brew to upgrade to asdf 7.3 before uninstalling and reinstalling the ruby version as seen above.

Something seems to be broken with the way rubygems sees the installed gems. After installing a second bundler version (`gem install bundler --version 1.17.3`), I get this:

```
> gem list --local

*** LOCAL GEMS ***

bigdecimal (default: 1.3.4)
bundler (2.0.2, 1.17.3)
cmath (default: 1.0.0)
```

However, the uninstall command doesn't work:

```
> gem uninstall -a bundler
Gem 'bundler' is not installed
```

**Comment by robacarp** [comment]
After switching back to rbenv, and the same issue presented itself, I found [some documentation on bundler.io](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html) about this problem. Bottom line is, It's a rubygems bug, not an asdf or bundler bug.

Solution is: `gem update --system`

Sorry for the churn, and thanks for asdf-ruby!

**Comment by Stratus3D** [comment]
Thanks for reporting @robacarp. If there is anything we can do to improve the asdf-ruby docs feel free to open another issue or a PR.
