### ISSUE TITLE
Unable to install ruby v2.4.8

### ISSUE THREAD

**Issue by vraravam** [asdf-vm/asdf-ruby#140]
I had used `ruby 2.4.2` when developing a rails app some months ago. Since then, `ruby 2.4.8` has been released as a security release. I was trying to upgrade by manually updating the `.tool-versions` file, and running `asdf install` - which has worked fine before (some months ago).

**Comment by vraravam** [comment]
This is the stack trace from the generated log file:
```
./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems -r./x86_64-darwin18-fake ./tool/rbinstall.rb --make="make" --dest-dir="" --extout=".ext" --mflags="" --make-flags="" --data-mode=0644 --prog-mode=0755 --installed-list .installed.list --mantype="doc" --install=all --rdoc-output=".ext/rdoc"
installing binary commands:   /Users/vijay/.asdf/installs/ruby/2.4.8/bin
installing base libraries:    /Users/vijay/.asdf/installs/ruby/2.4.8/lib
installing arch files:        /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/2.4.0/x86_64-darwin18
installing pkgconfig data:    /Users/vijay/.asdf/installs/ruby/2.4.8/lib/pkgconfig
installing command scripts:   /Users/vijay/.asdf/installs/ruby/2.4.8/bin
installing library scripts:   /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/2.4.0
installing common headers:    /Users/vijay/.asdf/installs/ruby/2.4.8/include/ruby-2.4.0
installing manpages:          /Users/vijay/.asdf/installs/ruby/2.4.8/share/man/man1
installing extension objects: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/2.4.0/x86_64-darwin18
installing extension objects: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/site_ruby/2.4.0/x86_64-darwin18
installing extension objects: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/vendor_ruby/2.4.0/x86_64-darwin18
installing extension headers: /Users/vijay/.asdf/installs/ruby/2.4.8/include/ruby-2.4.0/x86_64-darwin18
installing extension scripts: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/2.4.0
installing extension scripts: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/site_ruby/2.4.0
installing extension scripts: /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/vendor_ruby/2.4.0
installing extension headers: /Users/vijay/.asdf/installs/ruby/2.4.8/include/ruby-2.4.0/ruby
installing default gems:      /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
                              bigdecimal 1.3.2
                              io-console 0.4.6
                              json 2.0.4
                              openssl 2.0.9
                              psych 2.2.2
                              rdoc 5.0.1
installing bundle gems:       /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/gems/2.4.0 (build_info, cache, doc, extensions, gems, specifications)
/private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:383:in `initialize': Permission denied @ rb_sysopen - /Users/vijay/.asdf/installs/ruby/2.4.8/lib/ruby/gems/2.4.0/gems/minitest-5.10.1/.autotest (Errno::EACCES)
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:383:in `open'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:383:in `block (2 levels) in extract_tar_gz'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:365:in `block in extract_tar_gz'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:492:in `block in open_tar_gz'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:489:in `wrap'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:489:in `open_tar_gz'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:364:in `extract_tar_gz'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:345:in `block (2 levels) in extract_files'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package/tar_reader.rb:65:in `each'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:342:in `block in extract_files'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `open'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package/file_source.rb:30:in `with_read_io'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/package.rb:339:in `extract_files'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/installer.rb:801:in `extract_files'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/installer.rb:302:in `install'
	from ./tool/rbinstall.rb:685:in `call'
	from ./tool/rbinstall.rb:685:in `block in <class:Installer>'
	from ./tool/rbinstall.rb:784:in `block (3 levels) in <main>'
	from /private/var/folders/qg/fzgvx8q560qf26jdxgkw7xcw0000gq/T/ruby-build.20191017215105.9659/ruby-2.4.8/lib/rubygems/user_interaction.rb:51:in `use_ui'
	from ./tool/rbinstall.rb:784:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:780:in `each'
	from ./tool/rbinstall.rb:780:in `block in <main>'
	from ./tool/rbinstall.rb:822:in `block in <main>'
	from ./tool/rbinstall.rb:819:in `each'
	from ./tool/rbinstall.rb:819:in `<main>'
make: *** [do-install-all] Error 1
```

**Comment by Stratus3D** [comment]
Make sure you are using the latest version of asdf-ruby and see the discussion on https://github.com/rbenv/ruby-build/issues/1354.
