### ISSUE TITLE
can't install ruby 2.5.0-dev

### ISSUE THREAD

**Issue by caduguedess** [asdf-vm/asdf-ruby#171]
I already updated the ruby asdf plugin but I'm getting this error

```
carlos@cadu:~$ asdf install ruby 2.5.0-dev
Cloning https://github.com/ruby/ruby.git...
Installing ruby-2.5.0-dev...

BUILD FAILED (Ubuntu 20.04 using ruby-build 20200401)

Inspect or clean up the working tree at /tmp/ruby-build.20200524123620.32223.ovIf9B
Results logged to /tmp/ruby-build.20200524123620.32223.log

Last 10 log lines:
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:235:in `block in open_loop'
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:233:in `catch'
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:233:in `open_loop'
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:174:in `open_uri'
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:744:in `open'
        from /home/carlos/.asdf/installs/ruby/2.7.1/lib/ruby/2.7.0/open-uri.rb:752:in `read'
        from /tmp/ruby-build.20200524123620.32223.ovIf9B/ruby-2.5.0-dev/tool/downloader.rb:164:in `download'
        from /tmp/ruby-build.20200524123620.32223.ovIf9B/ruby-2.5.0-dev/tool/downloader.rb:66:in `download'
        from -e:4:in `<main>'
make: *** [uncommon.mk:1140: update-gems] Error 1
```

Here follows the entire log 
https://gist.github.com/caduguedess/70a6a2d0c3d074a0f281e5d742dfe82a

**Comment by caduguedess** [comment]
This solved the issue
`apt-get install autoconf bison build-essential libssl-dev libyaml-dev libreadline6-dev zlib1g-dev libncurses5-dev libffi-dev libgdbm6 libgdbm-dev libdb-dev
`
