### ISSUE TITLE
Problems when running rspec

### ISSUE THREAD

**Issue by axcdnt** [asdf-vm/asdf-ruby#230]
I've recently found a problem when trying to run RSpec. After years using asdf, this is the first time I hit a wall with my setup:
```
➜ bundle exec rspec
bundler: failed to load command: rspec (/Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec)
LoadError: cannot load such file -- equire
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `require'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `block in requires='
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `each'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration.rb:1453:in `requires='
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:112:in `block in process_options_into'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `each'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:111:in `process_options_into'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/configuration_options.rb:21:in `configure'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:99:in `setup'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:86:in `run'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:71:in `run'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.6.0/exe/rspec:4:in `<top (required)>'
  /Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec:23:in `load'
  /Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
```

Environment:

```
OS:
Darwin macbook.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

SHELL:
zsh 5.8 (x86_64-apple-darwin20.0)

ASDF VERSION:
v0.8.1-847ec73

ASDF ENVIRONMENT VARIABLES:
ASDF_DIR=/Users/<username>/.asdf

ASDF INSTALLED PLUGINS:
ruby                         https://github.com/asdf-vm/asdf-ruby.git master 6e51861
```

Tests:

- Completely remove asdf via `brew uninstall asdf`, without success
- Remove all shims, reinstall Ruby and `bundle exec rspec`, without success
- Install asdf via git
- Reshim versions
- Installing different Ruby versions
- Different RSpec versions, same error
- I can succesfully run other commands like `bundle exec rackup` or `bundle exec rails s`

How to reproduce:

1. `asdf install ruby 2.7.0`
2. `gem install rails`
3. `rails new example-app`
4. `bundle add rspec --group "development, test"`
5. `bundle add rspec-rails --group "development, test"`
6. `bundle exec rspec`

Output:

```
bundler: failed to load command: rspec (/Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec)
LoadError: cannot load such file -- equire
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1292:in `require'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1292:in `block in requires='
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1292:in `each'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration.rb:1292:in `requires='
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration_options.rb:109:in `block in process_options_into'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration_options.rb:108:in `each'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration_options.rb:108:in `process_options_into'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/configuration_options.rb:21:in `configure'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:105:in `setup'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:92:in `run'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:78:in `run'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/lib/rspec/core/runner.rb:45:in `invoke'
  /Users/<username>/.asdf/installs/ruby/2.7.0/lib/ruby/gems/2.7.0/gems/rspec-core-3.5.0.beta3/exe/rspec:4:in `<top (required)>'
  /Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec:23:in `load'
  /Users/<username>/.asdf/installs/ruby/2.7.0/bin/rspec:23:in `<top (required)>'
```

Let me know if there's something else I should add here.

**Comment by Stratus3D** [comment]
Do you know what this line means? `LoadError: cannot load such file -- equire`

It's not clear to me what `equire` is, but a quick google search doesn't return any relevant results. Is it possible that the beta version of rspec or some other code in your project contains a typo? `equire` looks a lot like `require`, which is a ruby keyword I believe.

**Comment by axcdnt** [comment]
@Stratus3D, thanks for the follow-up! It's very likely that a `require` is broken, but I have no idea why and where.
 
I did the exact same search here before creating the issue. I guess we can close this issue as I believe it's very _unique_ to my environment. However, I keep curious about what made it break.

Thank you!
