### ISSUE TITLE
Issue with `bundle` on 2.5.3

### ISSUE THREAD

**Issue by aturkewi** [asdf-vm/asdf-ruby#288]
I seem to be having an issue installing/using bundler with 2.5.3

After having run `asdf install ruby 2.5.3` and installing bundler with `gem install bundler` I get the following error:

```
$ bundle
Traceback (most recent call last):
	2: from /Users/aturkewi/.asdf/installs/ruby/2.5.3/bin/bundle:23:in `<main>'
	1: from /Users/aturkewi/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
/Users/aturkewi/.asdf/installs/ruby/2.5.3/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

I can try installing bundler again and I get:
```
$ gem install bundler
Successfully installed bundler-2.3.18
Parsing documentation for bundler-2.3.18
Done installing documentation for bundler after 0 seconds
1 gem installed
```

I can check that it's pulling from asdf with:
```
$ which bundler
/Users/aturkewi/.asdf/shims/bundler
```

And the shims are properly setup there (as far as I can tell):
```
$ cat /Users/aturkewi/.asdf/shims/bundler
#!/usr/bin/env bash
# asdf-plugin: ruby 2.5.3
# asdf-plugin: ruby 2.5.0
exec /usr/local/Cellar/asdf/0.10.2/libexec/bin/asdf exec "bundler" "$@" # asdf_allow: ' asdf '
```

So I seem to be able to install bundler and run it but then it cannot find itself. I'm wondering if it has something to do with the fact that the asdf path for ruby 2.5.3 has ruby 2.5.0 nested inside of it and that's where the error is coming from. That is very confusing to me. In a separate shell I set my ruby version to 2.5.0 and installed bundler to make sure it was installed there as well, but still no luck. Any help here would be much appreciated as I would have though it should be really easy to simply install ruby and run `bundle install`.

**Comment by aturkewi** [comment]
And an added note for anyone trying to install 2.5.3 right now, there is an openssl 1.1.1q issue when installing. It can be worked around using the flag mentioned here: https://github.com/rbenv/ruby-build/issues/1998#issuecomment-1180698666

**Comment by aturkewi** [comment]
Looks like this is actually a duplicate of #129 
I'm going to go ahead and close this.
