### ISSUE TITLE
asdf-ruby on macOS 12.6 Apple Silicon with rb 3.1.3 fails with install latest 

### ISSUE THREAD

**Issue by ylluminate** [asdf-vm/asdf-ruby#323]
```
$ asdf install ruby latest
To follow progress, use 'tail -f /var/folders/qt/ym5k8frn5x12m5cmc9fn087r0000gn/T/ruby-build.20221202174504.62275.log' or pass --verbose
Downloading openssl-3.0.7.tar.gz...
-> https://dqw8nmjcqpjn7.cloudfront.net/83049d042a260e696f62406ac5c08bf706fd84383f945cf21bd61e9ed95c396e
Installing openssl-3.0.7...
Installed openssl-3.0.7 to /Users/user/.asdf/installs/ruby/3.1.3

Downloading ruby-3.1.3.tar.gz...
-> https://cache.ruby-lang.org/pub/ruby/3.1/ruby-3.1.3.tar.gz
Installing ruby-3.1.3...
ruby-build: using readline from homebrew
ruby-build: using gmp from homebrew

BUILD FAILED (macOS 12.6.2 using ruby-build 20221124)

Inspect or clean up the working tree at /var/folders/qt/ym5k8frn5x12m5cmc9fn087r0000gn/T/ruby-build.20221202174504.62275.R9nz9x
Results logged to /var/folders/qt/ym5k8frn5x12m5cmc9fn087r0000gn/T/ruby-build.20221202174504.62275.log

Last 10 log lines:
	from ./tool/rbinstall.rb:899:in `block in install'
	from ./tool/rbinstall.rb:713:in `no_write'
	from ./tool/rbinstall.rb:899:in `install'
	from ./tool/rbinstall.rb:1060:in `block (2 levels) in <main>'
	from ./tool/rbinstall.rb:1044:in `foreach'
	from ./tool/rbinstall.rb:1044:in `block in <main>'
	from ./tool/rbinstall.rb:1116:in `block in <main>'
	from ./tool/rbinstall.rb:1113:in `each'
	from ./tool/rbinstall.rb:1113:in `<main>'
make: *** [do-install-all] Error 1
```

Full log: [ruby-build.20221202174504.62275.log](https://p153.p0.n0.cdn.getcloudapp.com/items/2Nu6Azqe/2efd6b38-fdc2-42c1-abc3-cb5db59e1f1c.log?v=6db6acf7296a686af463e1849f5f9289)

**Comment by joseneto** [comment]
Same here, I can install the 3.2.2 but its failed when I try install the 3.1.3

**Comment by DarlonHenrique** [comment]
same here, apple macbook pro m3

```
BUILD FAILED (macOS 14.4 on arm64 using ruby-build 20240709.1)
```

**Comment by jdx** [comment]
definitely nothing to do with asdf, mise, or asdf-ruby

**Comment by DarlonHenrique** [comment]
i solve the issue for me running the commands to install the system dependencies listed here: https://github.com/rbenv/ruby-build/wiki#suggested-build-environment

in my case using using a MacOs 14.5 (23F79) was that commands: 

```sh
# install Xcode Command Line Tools
xcode-select --install
# install dependencies with Homebrew
brew install openssl@3 readline libyaml gmp
```

after that i remove the plugin  
```sh 
asdf plugin remove ruby
# asdf plugin remove erlang
```

and add again with
```sh
asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
```
